# Generated by Django 5.2.1 on 2025-05-11 13:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicRank",
            fields=[
                (
                    "rank_id",
                    models.SmallIntegerField(primary_key=True, serialize=False),
                ),
                ("rank_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="AccommodationType",
            fields=[
                (
                    "acc_type",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("address_id", models.AutoField(primary_key=True, serialize=False)),
                ("line1", models.CharField(max_length=120)),
                ("line2", models.CharField(blank=True, max_length=120, null=True)),
                ("city", models.CharField(max_length=60)),
                ("province", models.CharField(max_length=60)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=60)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminPosition",
            fields=[
                ("position_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=60)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("school", "School"),
                            ("department", "Department"),
                            ("program", "Program"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssessmentItem",
            fields=[
                ("item_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("item_name", models.CharField(max_length=60)),
                (
                    "weight_percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("due_datetime", models.DateTimeField()),
                ("allow_multiple_attempts", models.BooleanField(default=False)),
                (
                    "max_attempts",
                    models.SmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_code",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=120)),
                ("credit_value", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "default_grading_scheme",
                    models.CharField(
                        choices=[
                            ("letter", "Letter"),
                            ("percent", "Percent"),
                            ("passfail", "Pass/Fail"),
                        ],
                        max_length=10,
                    ),
                ),
                ("syllabus_blob", models.TextField(blank=True, null=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("CN", "Chinese"),
                            ("EN", "English"),
                            ("BI", "Bilingual"),
                        ],
                        max_length=2,
                    ),
                ),
                ("canonical_flag", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("dept_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("office_location", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                ("inst_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("main", "Main"),
                            ("branch", "Branch"),
                            ("partner", "Partner"),
                            ("online", "Online"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "accreditation_level",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "staff_id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("hire_date", models.DateField()),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full-time", "Full-time"),
                            ("part-time", "Part-time"),
                            ("adjunct", "Adjunct"),
                            ("GTA", "GTA"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "staff_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("leave", "Leave"),
                            ("retired", "Retired"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeaveReason",
            fields=[
                (
                    "reason_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "person_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("legal_name", models.CharField(max_length=100)),
                ("preferred_name", models.CharField(max_length=100)),
                (
                    "sex_at_birth",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("U", "Undefined")],
                        max_length=1,
                    ),
                ),
                (
                    "gender_identity",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("birth_date", models.DateField()),
                ("national_id", models.CharField(max_length=30, unique=True)),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("email", models.EmailField(max_length=100, unique=True)),
                (
                    "primary_address_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="DBMS.address",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                ("program_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                (
                    "degree_type",
                    models.CharField(
                        choices=[
                            ("BA", "BA"),
                            ("BSc", "BSc"),
                            ("MSc", "MSc"),
                            ("MEng", "MEng"),
                            ("PhD", "PhD"),
                            ("Integrated", "Integrated"),
                        ],
                        max_length=10,
                    ),
                ),
                ("credit_required", models.SmallIntegerField()),
                (
                    "gpa_min_required",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=3,
                        validators=[django.core.validators.MinValueValidator(2.0)],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "term_code",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("description", models.CharField(blank=True, max_length=60, null=True)),
                ("is_current_term", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="AssessmentSubmission",
            fields=[
                (
                    "submission_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "attempt_no",
                    models.SmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("submit_time", models.DateTimeField(auto_now_add=True)),
                (
                    "score_raw",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("file_link", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DBMS.assessmentitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssessmentFeedback",
            fields=[
                ("feedback_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[("text", "Text"), ("rubric", "Rubric")], max_length=10
                    ),
                ),
                ("content", models.JSONField()),
                (
                    "submission_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DBMS.assessmentsubmission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Competency",
            fields=[
                ("comp_id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=120)),
                ("level_scale", models.JSONField()),
                (
                    "linked_course_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="DBMS.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseOffering",
            fields=[
                ("offering_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("section_number", models.CharField(max_length=5)),
                (
                    "delivery_mode",
                    models.CharField(
                        choices=[
                            ("in-person", "In-person"),
                            ("online", "Online"),
                            ("hybrid", "Hybrid"),
                            ("self-paced", "Self-paced"),
                        ],
                        max_length=10,
                    ),
                ),
                ("campus", models.CharField(max_length=40)),
                ("room_id", models.CharField(blank=True, max_length=20, null=True)),
                ("capacity", models.SmallIntegerField()),
                ("waitlist_capacity", models.SmallIntegerField(default=0)),
                (
                    "cross_list_group",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("waitlist", "Waitlist"),
                            ("cancelled", "Cancelled"),
                            ("merged", "Merged"),
                        ],
                        max_length=10,
                    ),
                ),
                ("duration_terms", models.SmallIntegerField(default=1)),
                (
                    "course_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.course"
                    ),
                ),
                (
                    "term_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.term"
                    ),
                ),
            ],
            options={
                "unique_together": {("course_code", "term_code", "section_number")},
            },
        ),
        migrations.AddField(
            model_name="assessmentitem",
            name="offering_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="DBMS.courseoffering"
            ),
        ),
        migrations.CreateModel(
            name="CourseRequisite",
            fields=[
                (
                    "CR_id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                (
                    "min_grade_required",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("concurrent_allowed", models.BooleanField(default=False)),
                (
                    "course_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisites",
                        to="DBMS.course",
                    ),
                ),
                (
                    "prereq_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_for",
                        to="DBMS.course",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="owning_dept_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="DBMS.department"
            ),
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "class_id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("cohort_year", models.SmallIntegerField()),
                ("class_name", models.CharField(max_length=60)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("on-campus", "On-campus"),
                            ("online", "Online"),
                            ("mixed", "Mixed"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("merged", "Merged"),
                            ("dissolved", "Dissolved"),
                        ],
                        max_length=10,
                    ),
                ),
                ("note_json", models.JSONField(blank=True, null=True)),
                (
                    "dept_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DBMS.department",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="department",
            name="inst_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="DBMS.institution"
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="chair_staff_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="DBMS.staff"
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="person_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="DBMS.person"
            ),
        ),
        migrations.CreateModel(
            name="NameHistory",
            fields=[
                ("history_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("old_name", models.CharField(max_length=100)),
                ("new_name", models.CharField(max_length=100)),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="DBMS.staff",
                    ),
                ),
                (
                    "person_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.person"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectTeam",
            fields=[
                ("team_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("project_title", models.CharField(max_length=120)),
                (
                    "advisor_staff_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.staff"
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DBMS.courseoffering",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RewardPunish",
            fields=[
                ("remark_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("remark_type", models.CharField(max_length=20)),
                ("remark_value", models.CharField(max_length=200)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.person"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="DBMS.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "student_id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("admission_year", models.SmallIntegerField()),
                (
                    "enrollment_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("leave", "Leave"),
                            ("graduate", "Graduate"),
                            ("dismissed", "Dismissed"),
                        ],
                        max_length=10,
                    ),
                ),
                ("expected_grad_term", models.CharField(max_length=6)),
                ("disability_flag", models.BooleanField(default=False)),
                (
                    "person_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.person"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LearningEvent",
            fields=[
                ("event_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=30)),
                ("timestamp", models.DateTimeField()),
                ("metadata_json", models.JSONField(blank=True, null=True)),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DBMS.courseoffering",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GradeAppeal",
            fields=[
                ("appeal_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("appeal_date", models.DateField(auto_now_add=True)),
                ("appeal_reason", models.TextField()),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("resolution_note", models.TextField(blank=True, null=True)),
                (
                    "item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DBMS.assessmentitem",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="DBMS.staff",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnrollmentOverride",
            fields=[
                ("override_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "override_type",
                    models.CharField(
                        choices=[("credit", "Credit"), ("prereq", "Prerequisite")],
                        max_length=10,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "offering_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DBMS.courseoffering",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.staff"
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DisabilityAccommodation",
            fields=[
                ("acc_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("active_from", models.DateField()),
                ("active_to", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "acc_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DBMS.accommodationtype",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseWaiverRequest",
            fields=[
                ("waiver_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "reason_type",
                    models.CharField(
                        choices=[
                            ("placement-test", "Placement Test"),
                            ("competency", "Competency"),
                            ("certificate", "Certificate"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "evidence_link",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("request_date", models.DateField(auto_now_add=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("decision_date", models.DateField(blank=True, null=True)),
                (
                    "course_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.course"
                    ),
                ),
                (
                    "decision_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="DBMS.staff",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.student"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assessmentsubmission",
            name="student_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="DBMS.student"
            ),
        ),
        migrations.CreateModel(
            name="AcademicIncident",
            fields=[
                ("incident_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("incident_type", models.CharField(max_length=40)),
                ("report_date", models.DateField()),
                ("status", models.CharField(max_length=20)),
                ("penalty_description", models.TextField(blank=True, null=True)),
                (
                    "offering_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="DBMS.courseoffering",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.staff"
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeaveOfAbsence",
            fields=[
                ("loa_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "documentation_link",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("description", models.CharField(max_length=60)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="DBMS.staff",
                    ),
                ),
                (
                    "reason_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DBMS.leavereason",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.student"
                    ),
                ),
                (
                    "end_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_end_terms",
                        to="DBMS.term",
                    ),
                ),
                (
                    "start_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_start_terms",
                        to="DBMS.term",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstructorLeave",
            fields=[
                ("leave_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("sabbatical", "Sabbatical"),
                            ("parental", "Parental"),
                            ("sick", "Sick"),
                        ],
                        max_length=10,
                    ),
                ),
                ("replacement_required_flag", models.BooleanField(default=False)),
                (
                    "staff_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.staff"
                    ),
                ),
                (
                    "leave_end_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor_leave_ends",
                        to="DBMS.term",
                    ),
                ),
                (
                    "leave_start_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor_leave_starts",
                        to="DBMS.term",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExchangeEnrollment",
            fields=[
                ("exch_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "host_program_id",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("credit_load", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in-progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        max_length=15,
                    ),
                ),
                ("transcript_received_flag", models.BooleanField(default=False)),
                (
                    "host_inst_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DBMS.institution",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.student"
                    ),
                ),
                (
                    "host_term_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.term"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransferredCredit",
            fields=[
                ("tc_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("host_course_code", models.CharField(max_length=20)),
                ("host_grade", models.CharField(max_length=8)),
                ("host_credit", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "credit_accepted",
                    models.DecimalField(decimal_places=1, max_digits=4),
                ),
                ("decision_date", models.DateField(auto_now_add=True)),
                (
                    "decision_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.staff"
                    ),
                ),
                (
                    "exch_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DBMS.exchangeenrollment",
                    ),
                ),
                (
                    "mapped_course_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DBMS.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClassCoursePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("compulsory_flag", models.BooleanField()),
                ("planned_week", models.SmallIntegerField(blank=True, null=True)),
                ("remark", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "class_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.class"
                    ),
                ),
                (
                    "offering_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DBMS.courseoffering",
                    ),
                ),
            ],
            options={
                "unique_together": {("class_id", "offering_id")},
            },
        ),
        migrations.CreateModel(
            name="InstructorRole",
            fields=[
                (
                    "staff_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="DBMS.staff",
                    ),
                ),
                (
                    "primary_dept_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "academic_rank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DBMS.academicrank",
                    ),
                ),
                (
                    "end_term_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instructor_end_terms",
                        to="DBMS.term",
                    ),
                ),
                (
                    "primary_dept_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DBMS.department",
                    ),
                ),
                (
                    "start_term_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor_start_terms",
                        to="DBMS.term",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgramAffiliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "affiliation_type",
                    models.CharField(
                        choices=[("host", "Host"), ("co-host", "Co-host")],
                        max_length=10,
                    ),
                ),
                (
                    "dept_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DBMS.department",
                    ),
                ),
                (
                    "program_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.program"
                    ),
                ),
            ],
            options={
                "unique_together": {("program_id", "dept_id")},
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enroll_state",
                    models.CharField(
                        choices=[
                            ("added", "Added"),
                            ("waitlist", "Waitlist"),
                            ("dropped", "Dropped"),
                            ("audit", "Audit"),
                            ("waived", "Waived"),
                        ],
                        max_length=10,
                    ),
                ),
                ("enroll_date", models.DateField()),
                ("drop_date", models.DateField(blank=True, null=True)),
                ("grade_final", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "grade_points",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("repeat_flag", models.BooleanField(default=False)),
                (
                    "offering_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DBMS.courseoffering",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.student"
                    ),
                ),
            ],
            options={
                "unique_together": {("student_id", "offering_id")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="assessmentsubmission",
            unique_together={("item_id", "student_id", "attempt_no")},
        ),
        migrations.CreateModel(
            name="StudentCompetency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("competency_level", models.CharField(max_length=25)),
                (
                    "evidence_link",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("verify_date", models.DateField()),
                (
                    "comp_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DBMS.competency",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.student"
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.staff"
                    ),
                ),
            ],
            options={
                "unique_together": {("student_id", "comp_id")},
            },
        ),
        migrations.CreateModel(
            name="TeachAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("co", "Co-instructor"),
                            ("TA", "Teaching Assistant"),
                            ("industrymentor", "Industry Mentor"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "pay_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "offering_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DBMS.courseoffering",
                    ),
                ),
                (
                    "staff_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.staff"
                    ),
                ),
            ],
            options={
                "unique_together": {("offering_id", "staff_id")},
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_in_team",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("join_date", models.DateField()),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.student"
                    ),
                ),
                (
                    "team_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DBMS.projectteam",
                    ),
                ),
            ],
            options={
                "unique_together": {("team_id", "student_id")},
            },
        ),
        migrations.CreateModel(
            name="StudentProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_primary_major", models.BooleanField(default=True)),
                (
                    "program_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.program"
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.student"
                    ),
                ),
                (
                    "end_term",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_program_ends",
                        to="DBMS.term",
                    ),
                ),
                (
                    "start_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_program_starts",
                        to="DBMS.term",
                    ),
                ),
            ],
            options={
                "unique_together": {("student_id", "program_id")},
            },
        ),
        migrations.CreateModel(
            name="StudentClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_in_class",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "class_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.class"
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.student"
                    ),
                ),
                (
                    "end_term",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_class_ends",
                        to="DBMS.term",
                    ),
                ),
                (
                    "start_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_class_starts",
                        to="DBMS.term",
                    ),
                ),
            ],
            options={
                "unique_together": {("student_id", "class_id")},
            },
        ),
        migrations.CreateModel(
            name="ClassAdvisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "advisor_role",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("mental", "Mental"),
                            ("career", "Career"),
                            ("deputy", "Deputy"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_primary", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "class_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.class"
                    ),
                ),
                (
                    "staff_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.staff"
                    ),
                ),
                (
                    "end_term",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="advisor_end_terms",
                        to="DBMS.term",
                    ),
                ),
                (
                    "start_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advisor_start_terms",
                        to="DBMS.term",
                    ),
                ),
            ],
            options={
                "unique_together": {("class_id", "staff_id")},
            },
        ),
        migrations.CreateModel(
            name="AdminRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DBMS.adminposition",
                    ),
                ),
                (
                    "staff_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DBMS.staff"
                    ),
                ),
                (
                    "end_term_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_end_terms",
                        to="DBMS.term",
                    ),
                ),
                (
                    "start_term_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_start_terms",
                        to="DBMS.term",
                    ),
                ),
            ],
            options={
                "unique_together": {("staff_id", "position_id")},
            },
        ),
    ]
