# Generated by Django 5.2.1 on 2025-05-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DBMS", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="type",
            field=models.CharField(
                choices=[
                    ("main", "Main"),
                    ("branch", "Branch"),
                    ("partner", "Partner"),
                    ("online", "Online"),
                ],
                max_length=15,
            ),
        ),
    ]
