# Generated by Django 5.2.1 on 2025-05-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DBMS", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="primary_address",
            new_name="primary_address_id",
        ),
        migrations.RenameField(
            model_name="rewardpunish",
            old_name="person",
            new_name="person_id",
        ),
    ]
