# Generated by Django 5.2.1 on 2025-05-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DBMS", "0002_alter_institution_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leavereason",
            name="reason_code",
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
