# Generated by Django 5.2.1 on 2025-05-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DBMS", "0003_rename_offering_academicincident_offering_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentcompetency",
            name="competency_level",
            field=models.CharField(max_length=25),
        ),
    ]
